# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildApp
    displayName: Buils Apps
    jobs:
      - job: BuilFrontendApp
        displayName: Build Fontend App
        steps:
          - script: echo building fontend app
            displayName: build frontend app
          - script: echo running unit tests for frintend app
            displayName: unit tests frontend

      - job: BuildBackendApp
        displayName: Buils Backend App
        steps:
          - script: echo building backend app
            displayName: build backend app
          - script: echo running unit tests for backend app
            displayName: unit tests backend

  - stage: DeployDev
    displayName: Deploy to Dev environment
    dependsOn: []
    jobs:
      - job: DeployFrontendDev
        displayName: Deploy frontend to DEV
        steps:
          - script: echo deploying frontend app to DEV
            displayName: deploy forntend app to DEV

      - job: DeployBackendDev
        displayName: Deploy backend to DEV
        steps:
          - script: echo deploying backend app to DEV
            displayName: deploy backend app to DEV

  - stage: DeployProd
    displayName: Deploy to PROD enviroment
    dependsOn: []
    pool:
      vmImage: 'macOS-latest'
    jobs:
      - job: DeployFrontendProd
        displayName: Deploy frontend to PROD
        steps:
          - script: echo deploying frontend app to PROD
            displayName: deploy frontend app to PROD

      - job: DeployBackendProd
        displayName: Deploy backend app to PROD
        pool:
          vmImage: 'vs2017-win2016'
        steps:
          - script: echo deploying backend app to PROD
            displayName: deploy backend app to PROD